game: huginn-fps-demo
image: us-central1-docker.pkg.dev/project-79591f24-2c6a-498e-8b3/huginn-images/hugin-server:latest
min_instances: 3
max_instances: 10
buffer_size: 3
max_players: 10
port: 7778
udp_listen_addr: 0.0.0.0:9000
http_listen_addr: :8080
heartbeat_timeout_seconds: 15
mode: sdk
public_host: 136.115.141.26
cloud_provider: gcp
firewall_manage: true
