game: huginn-fps-demo
image: hugin-server:latest
min_instances: 3
max_instances: 19
buffer_size: 3
max_players: 10
port: 7778
udp_listen_addr: 0.0.0.0:9000
http_listen_addr: :8080
heartbeat_timeout_seconds: 15
mode: sdk
public_host: 136.115.141.26
cloud_provider: gcp
